LOG_PERIOD: 200
TRAIN:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
  EVAL_PERIOD: 5
  EVAL_FEATURE: True
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /home/keyu/logs/test/checkpoints/checkpoint_epoch_00100.pyth
DATA:
  NORMALIZATION: False
  TARGET_FPS: 25
  MULTI_CLIP_NUM: 2
  NUM_FRAMES: 16
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  RANDOM_FLIP: True
  CVRL_AUG: True
  KEEP_ORIGIN: True
  AUG:
    COLOR_JITTER_PROB: 0.8
    BRIGHTNESS_FACTOR: 0.8
    CONTRAST_FACTOR: 0.8 
    SATURATION_FACTOR: 0.8
    HUE_FACTOR: 0.2
    GREYSCALE_PROB: 0.2
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: dot_product
BN:
  SHUFFLE_BN: True
  NORM_TYPE: batchnorm
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.32
  LR_POLICY: cosine
  MAX_EPOCH: 196
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-6
  CLS_WEIGHT_DECAY: 0.0
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.0
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 400
  NUM_EMBEDDING: 128
  NUM_FEATURE: 2048
  ARCH: cvrl
  MODEL_NAME: ResNet
  LOSS_FUNC: multi_label_cce
  DROPOUT_RATE: 0.
  CLASSIFIER: LinearProbe
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 32
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /home/keyu/logs/qe_5_thresh_085
NCE:
  K: 16384
  T: 0.1
  M: 0.5
  ALPHA: 0.999
  THRESH: 0.85
  TOPK: 1
  SELECTION: thresh
  QE: True
  QE_NUM: 5
