LOG_PERIOD: 100
TRAIN:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 64
  PSEUDO_BATCH: 16
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: /home/keyu/keyu/ckpt/slowfast_4x16.pkl
  CHECKPOINT_TYPE: caffe2
DATA:
  PATH_TO_DATA_DIR: /home/keyu/keyu/data/UCF101/cls_balance_010
  NORMALIZATION: True
  TARGET_FPS: 25
  MULTI_CLIP_NUM: 1
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  RANDOM_FLIP: True
  CVRL_AUG: False
  AUG:
    COLOR_JITTER_PROB: 0.8
    BRIGHTNESS_FACTOR: 0.8
    CONTRAST_FACTOR: 0.8 
    SATURATION_FACTOR: 0.8
    HUE_FACTOR: 0.2
    GREYSCALE_PROB: 0.2
SLOWFAST:
  ALPHA: 8
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 50
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 32.0
  LR_POLICY: cosine
  MAX_EPOCH: 196
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 1.0
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 101
  NUM_EMBEDDING: 128
  NUM_FEATURE: 2304
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.
  CLASSIFIER: LinearProbe
  FEATURE_L2: False
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 64
EVAL:
  ENABLE: True
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /home/keyu/keyu/logs/UCF_eval/fixed/UCF_cb_010_sf_4x16_196_not_l2_largeLR
